#include "main.h"
#include "string.h"
#include "icm20948-register.h"
#include <stdio.h>

// Constants
#define GPS_ADDR 0x10
#define IMU_ADDR 0x69
#define MAX_BUFFER_SIZE 250
#define CAMERA_BUFFER_SIZE 4096

// Buffers
char uart_buffer[MAX_BUFFER_SIZE];
char gps_buffer[MAX_BUFFER_SIZE];
uint8_t camera_buffer[CAMERA_BUFFER_SIZE];
int16_t imu_data[3];

// Global Handles
I2C_HandleTypeDef hi2c2;
UART_HandleTypeDef huart2;
UART_HandleTypeDef huart3;

// Init Functions (Assume auto-generated by CubeMX)
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C2_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_USART3_UART_Init(void);

void gps_init(void);
void gps_read_and_parse(char *gps_buffer);
void icm20948_init(void);
void icm20948_read_accel(int16_t *imu_data);

int read_openmv_frame(void);
void send_combined_data(void);

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C2_Init();
    MX_USART2_UART_Init();
    MX_USART3_UART_Init();

    snprintf(uart_buffer, sizeof(uart_buffer), "Starting system...\n");
    HAL_UART_Transmit(&huart3, (uint8_t *)uart_buffer, strlen(uart_buffer), HAL_MAX_DELAY);

    icm20948_init();
    gps_init();

    while (1) {
        send_combined_data();
        HAL_Delay(500);  // Control frame rate
    }
}

// Read complete frame from OpenMV (JPEG ends with 0xFFD9)
int read_openmv_frame() {
    memset(camera_buffer, 0, CAMERA_BUFFER_SIZE);
    uint16_t idx = 0;
    while (idx < CAMERA_BUFFER_SIZE - 1) {
        HAL_UART_Receive(&huart2, &camera_buffer[idx], 1, 100);  // timeout after 100ms
        if (idx > 0 && camera_buffer[idx - 1] == 0xFF && camera_buffer[idx] == 0xD9) {
            idx++;
            break;
        }
        idx++;
    }
    return idx;
}

// Send combined GPS, IMU, and Camera Data to Raspberry Pi
void send_combined_data() {
    memset(gps_buffer, 0, sizeof(gps_buffer));
    gps_read_and_parse(gps_buffer);

    icm20948_read_accel(imu_data);

    int img_length = read_openmv_frame();

    snprintf(uart_buffer, sizeof(uart_buffer),
             "<GPS>\n%s\n<GPS_END>\n"
             "<IMU>X=%d,Y=%d,Z=%d<\n"
             "<IMG_START>\n",
             gps_buffer, imu_data[0], imu_data[1], imu_data[2]);
    HAL_UART_Transmit(&huart3, (uint8_t*)uart_buffer, strlen(uart_buffer), HAL_MAX_DELAY);

    HAL_UART_Transmit(&huart3, camera_buffer, img_length, HAL_MAX_DELAY);

    const char img_end[] = "<IMG_END>\n";
    HAL_UART_Transmit(&huart3, (uint8_t*)img_end, strlen(img_end), HAL_MAX_DELAY);
}

// GPS Functions
void gps_init() {
    char init_command[] = "$PMTK314,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0*29\r\n";
    HAL_I2C_Master_Transmit(&hi2c2, GPS_ADDR << 1, (uint8_t*)init_command, strlen(init_command), HAL_MAX_DELAY);
}

void gps_read_and_parse(char *gps_buffer) {
    uint8_t buffer[MAX_BUFFER_SIZE];
    memset(buffer, 0, sizeof(buffer));

    HAL_I2C_Master_Receive(&hi2c2, GPS_ADDR << 1, buffer, sizeof(buffer), HAL_MAX_DELAY);

    char *gnrmc = strstr((char*)buffer, "GNRMC");
    if (gnrmc) {
        snprintf(gps_buffer, MAX_BUFFER_SIZE, "%s", gnrmc);
    } else {
        snprintf(gps_buffer, MAX_BUFFER_SIZE, "No GNRMC data found.");
    }
}

// IMU Functions
void icm20948_init() {
    uint8_t reg[2];
    reg[0] = PWR_MGMT_1; reg[1] = 0x00;
    HAL_I2C_Master_Transmit(&hi2c2, IMU_ADDR << 1, reg, 2, HAL_MAX_DELAY);

    reg[0] = ACCEL_CONFIG; reg[1] = 0x11;
    HAL_I2C_Master_Transmit(&hi2c2, IMU_ADDR << 1, reg, 2, HAL_MAX_DELAY);
}

void icm20948_read_accel(int16_t *imu_data) {
    uint8_t buffer[6];
    uint8_t reg = ACCEL_XOUT_H;
    HAL_I2C_Master_Transmit(&hi2c2, IMU_ADDR << 1, &reg, 1, HAL_MAX_DELAY);
    HAL_I2C_Master_Receive(&hi2c2, IMU_ADDR << 1, buffer, 6, HAL_MAX_DELAY);

    imu_data[0] = (buffer[0] << 8) | buffer[1];
    imu_data[1] = (buffer[2] << 8) | buffer[3];
    imu_data[2] = (buffer[4] << 8) | buffer[5];
}

// CubeMX-Generated UART2 Init for OpenMV
static void MX_USART2_UART_Init(void) {
    huart2.Instance = USART2;
    huart2.Init.BaudRate = 921600;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits = UART_STOPBITS_1;
    huart2.Init.Parity = UART_PARITY_NONE;
    huart2.Init.Mode = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    huart2.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
    huart2.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;

    if (HAL_UART_Init(&huart2) != HAL_OK) {
        Error_Handler();
    }
}

// CubeMX-Generated USART3 Init for RPi Link
static void MX_USART3_UART_Init(void) {
    huart3.Instance = USART3;
    huart3.Init.BaudRate = 115200;
    huart3.Init.WordLength = UART_WORDLENGTH_8B;
    huart3.Init.StopBits = UART_STOPBITS_1;
    huart3.Init.Parity = UART_PARITY_NONE;
    huart3.Init.Mode = UART_MODE_TX_RX;
    huart3.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart3.Init.OverSampling = UART_OVERSAMPLING_16;
    huart3.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
    huart3.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;

    if (HAL_UART_Init(&huart3) != HAL_OK) {
        Error_Handler();
    }
}
